/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_dcs_leef_jni_NativeTool */

#ifndef _Included_cn_dcs_leef_jni_NativeTool
#define _Included_cn_dcs_leef_jni_NativeTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dcs_leef_jni_NativeTool
 * Method:    basicTest
 * Signature: (ZBCSIJFD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_dcs_leef_jni_NativeTool_basicTest
  (JNIEnv *, jclass, jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble);

/*
 * Class:     cn_dcs_leef_jni_NativeTool
 * Method:    arrayTest
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_dcs_leef_jni_NativeTool_arrayTest
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_dcs_leef_jni_NativeTool
 * Method:    stringTest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_dcs_leef_jni_NativeTool_stringTest
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_dcs_leef_jni_NativeTool
 * Method:    classTest
 * Signature: (Lcn/dcs/leef/bean/UserJava;)Lcn/dcs/leef/bean/UserJava;
 */
JNIEXPORT jobject JNICALL Java_cn_dcs_leef_jni_NativeTool_classTest
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_dcs_leef_jni_NativeTool
 * Method:    methodTest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_dcs_leef_jni_NativeTool_methodTest
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
